<?php
/**
 * EbayOfferDetailsWithAllTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\EbayInventoryClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\EbayInventoryClient;

/**
 * EbayOfferDetailsWithAllTest Class Doc Comment
 *
 * @category    Class
 * @description This type provides details of an offer, and is used by the response payloads of the &lt;strong&gt;getOffer&lt;/strong&gt; and the &lt;strong&gt;getOffers&lt;/strong&gt; calls.
 * @package     Swagger\EbayInventoryClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EbayOfferDetailsWithAllTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EbayOfferDetailsWithAll"
     */
    public function testEbayOfferDetailsWithAll()
    {
    }

    /**
     * Test attribute "available_quantity"
     */
    public function testPropertyAvailableQuantity()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "charity"
     */
    public function testPropertyCharity()
    {
    }

    /**
     * Test attribute "format"
     */
    public function testPropertyFormat()
    {
    }

    /**
     * Test attribute "hide_buyer_details"
     */
    public function testPropertyHideBuyerDetails()
    {
    }

    /**
     * Test attribute "include_catalog_product_details"
     */
    public function testPropertyIncludeCatalogProductDetails()
    {
    }

    /**
     * Test attribute "listing"
     */
    public function testPropertyListing()
    {
    }

    /**
     * Test attribute "listing_description"
     */
    public function testPropertyListingDescription()
    {
    }

    /**
     * Test attribute "listing_duration"
     */
    public function testPropertyListingDuration()
    {
    }

    /**
     * Test attribute "listing_policies"
     */
    public function testPropertyListingPolicies()
    {
    }

    /**
     * Test attribute "listing_start_date"
     */
    public function testPropertyListingStartDate()
    {
    }

    /**
     * Test attribute "lot_size"
     */
    public function testPropertyLotSize()
    {
    }

    /**
     * Test attribute "marketplace_id"
     */
    public function testPropertyMarketplaceId()
    {
    }

    /**
     * Test attribute "merchant_location_key"
     */
    public function testPropertyMerchantLocationKey()
    {
    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {
    }

    /**
     * Test attribute "pricing_summary"
     */
    public function testPropertyPricingSummary()
    {
    }

    /**
     * Test attribute "quantity_limit_per_buyer"
     */
    public function testPropertyQuantityLimitPerBuyer()
    {
    }

    /**
     * Test attribute "secondary_category_id"
     */
    public function testPropertySecondaryCategoryId()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "store_category_names"
     */
    public function testPropertyStoreCategoryNames()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }
}
