<?php
/**
 * InventoryItemGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\EbayInventoryClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\EbayInventoryClient;

/**
 * InventoryItemGroupTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the base request payload of the &lt;strong&gt;createOrReplaceInventoryItemGroup&lt;/strong&gt; call and the base response payload of the &lt;strong&gt;getInventoryItemGroup&lt;/strong&gt; call.
 * @package     Swagger\EbayInventoryClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryItemGroupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryItemGroup"
     */
    public function testInventoryItemGroup()
    {
    }

    /**
     * Test attribute "aspects"
     */
    public function testPropertyAspects()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "image_urls"
     */
    public function testPropertyImageUrls()
    {
    }

    /**
     * Test attribute "inventory_item_group_key"
     */
    public function testPropertyInventoryItemGroupKey()
    {
    }

    /**
     * Test attribute "subtitle"
     */
    public function testPropertySubtitle()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "variant_sk_us"
     */
    public function testPropertyVariantSkUs()
    {
    }

    /**
     * Test attribute "varies_by"
     */
    public function testPropertyVariesBy()
    {
    }
}
